//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFMGenerator_Ocean.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DFMGenerator_Ocean.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        ///xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;meta name=ProgId content=Word.Document&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 15&quot;&gt;
        ///&lt;meta name=Originator content=&quot;Microsoft Word 15&quot;&gt;
        ///&lt;!--[if !mso]&gt;
        ///&lt;style&gt;
        ///v\:* {beh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFM_Generator_Petrel_UserGuide {
            get {
                return ResourceManager.GetString("DFM_Generator_Petrel_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DFMGenerator {
            get {
                object obj = ResourceManager.GetObject("DFMGenerator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Configuration Type=&quot;Configuration.ConfigurationState&quot; Version=&quot;1.0.0.12&quot; Caption=&quot;DFMGeneratorConfig&quot;&gt;
        ///  &lt;Extensions Type=&quot;Extensibility.ExtensionCollection&quot;&gt;
        ///    &lt;Workspaces.WorkspaceExtension EntityId=&quot;65641e60-2cf7-46db-9c41-f2a4c059d9ff&quot; /&gt;
        ///    &lt;Relationships.RelationshipsExtension&gt;
        ///      &lt;Associations Type=&quot;Relationships.Associations&quot;&gt;
        ///        &lt;Relationships.Association RelationshipId=&quot;Configuration-Section&quot; Role=&quot;Configuration&quot;&gt;
        ///          &lt;AssociatedEnds  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFMGeneratorConfig {
            get {
                return ResourceManager.GetString("DFMGeneratorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo1_256 {
            get {
                object obj = ResourceManager.GetObject("Logo1_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo1_48 {
            get {
                object obj = ResourceManager.GetObject("Logo1_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon P30_icon {
            get {
                object obj = ResourceManager.GetObject("P30_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon P32_icon {
            get {
                object obj = ResourceManager.GetObject("P32_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
